api = "0.2"

[buildpack]
id = "org.cloudfoundry.nginx"
name = "Nginx Server Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","bin/configure","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
nginx = "1.17.*"

[[metadata.dependencies]]
id = "nginx"
name = "Nginx Server"
sha256 = "79170f9a71673582ecf2cf0d3dcfbf110e42599b140882b6314bb3d097ee4f2a"
source = "http://nginx.org/download/nginx-1.15.12.tar.gz"
source_sha256 = "3d5b90aa17de1700709ae4ec6c4d73d87c888b06c510391bf7104b006fdb2abe"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.15.12-linux-x64-cflinuxfs3-79170f9a.tgz"
version = "1.15.12"

[[metadata.dependencies]]
id = "nginx"
name = "Nginx Server"
sha256 = "4d5e35adf40fdf16c4f2fce96bf2f56fa0daa140594af76bcf31bda85ffe2131"
source = "http://nginx.org/download/nginx-1.16.0.tar.gz"
source_sha256 = "4fd376bad78797e7f18094a00f0f1088259326436b537eb5af69b01be2ca1345"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.16.0-linux-x64-cflinuxfs3-4d5e35ad.tgz"
version = "1.16.0"

[[metadata.dependencies]]
id = "nginx"
name = "Nginx Server"
sha256 = "1c09ac0ccf5e66599419ac8e2917992b04db79756fc2c8b8ea5c9ca75b8118e3"
source = "http://nginx.org/download/nginx-1.16.1.tar.gz"
source_sha256 = "f11c2a6dd1d3515736f0324857957db2de98be862461b5a542a3ac6188dbe32b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.16.1-linux-x64-cflinuxfs3-1c09ac0c.tgz"
version = "1.16.1"

[[metadata.dependencies]]
id = "nginx"
name = "Nginx Server"
sha256 = "b9cfea16783b81e7462812ba4b95934dfa2334f01ed25a7057e7f45b6383fe66"
source = "http://nginx.org/download/nginx-1.17.1.tar.gz"
source_sha256 = "6f1825b4514e601579986035783769c456b888d3facbab78881ed9b58467e73e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.17.1-linux-x64-cflinuxfs3-b9cfea16.tgz"
version = "1.17.1"

[[metadata.dependencies]]
id = "nginx"
name = "Nginx Server"
sha256 = "935640a0b599c68eface2b91ea2971537431e881db3cbb6fc2b5391e793cc8cf"
source = "http://nginx.org/download/nginx-1.17.4.tar.gz"
source_sha256 = "62854b365e66670ef4f1f8cc79124f914551444da974207cd5fe22d85710e555"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.17.4-linux-x64-cflinuxfs3-935640a0.tgz"
version = "1.17.4"

[[metadata.dependency_deprecation_dates]]
date = 2019-05-21T00:00:00Z
link = "https://nginx.org/2018.html"
name = "nginx"
version_line = "1.15.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-04-01T00:00:00Z
link = "https://nginx.org/"
name = "nginx"
version_line = "1.16.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-05-01T00:00:00Z
link = "https://nginx.org/"
name = "nginx"
version_line = "1.17.x"

[metadata.version-lines]
mainline = "1.17.*"
stable = "1.16.*"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
