api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nginx"
  name = "Nginx Server Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "bin/configure", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.17.*"

  [[metadata.dependencies]]
    id = "nginx"
    name = "Nginx Server"
    sha256 = "4d5e35adf40fdf16c4f2fce96bf2f56fa0daa140594af76bcf31bda85ffe2131"
    source = "http://nginx.org/download/nginx-1.16.0.tar.gz"
    source_sha256 = "4fd376bad78797e7f18094a00f0f1088259326436b537eb5af69b01be2ca1345"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.16.0-linux-x64-cflinuxfs3-4d5e35ad.tgz"
    version = "1.16.0"

  [[metadata.dependencies]]
    id = "nginx"
    name = "Nginx Server"
    sha256 = "89a5c316a20cd2a4f44699cce0ba9962726b9795f8b3886f4c3e28cb3151b53d"
    source = "http://nginx.org/download/nginx-1.16.1.tar.gz"
    source_sha256 = "f11c2a6dd1d3515736f0324857957db2de98be862461b5a542a3ac6188dbe32b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.16.1-linux-x64-cflinuxfs3-89a5c316.tgz"
    version = "1.16.1"

  [[metadata.dependencies]]
    id = "nginx"
    name = "Nginx Server"
    sha256 = "06b8cb8a298c55340c8b36efd9ee0a5fcbe07216a05bb6527847383a4ed68cdf"
    source = "http://nginx.org/download/nginx-1.17.6.tar.gz"
    source_sha256 = "3cb4a5314dc0ab0a4e8a7b51ae17c027133417a45cc6c5a96e3dd80141c237b6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.17.6-linux-x64-cflinuxfs3-06b8cb8a.tgz"
    version = "1.17.6"

  [[metadata.dependencies]]
    id = "nginx"
    name = "Nginx Server"
    sha256 = "cb70ed43e4919f8bc236f5ec284513189082d537c9b7e8d9775cd95a0ee95461"
    source = "http://nginx.org/download/nginx-1.17.7.tar.gz"
    source_sha256 = "b62756842807e5693b794e5d0ae289bd8ae5b098e66538b2a91eb80f25c591ff"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.17.7-linux-x64-cflinuxfs3-cb70ed43.tgz"
    version = "1.17.7"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-04-01T00:00:00Z
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.16.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-05-01T00:00:00Z
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.17.x"
  [metadata.version-lines]
    mainline = "1.17.*"
    stable = "1.16.*"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
